name: CI

on: 
    workflow_dispatch:
    pull_request:

jobs:
    build-api:
        name: Build API
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Change directory
              run: cd ./api

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
                cache: "npm"
            
            - name: Build
              run: npm i && npm tsc

    build-ui:
        name: Build UI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Change directory
              run: cd ./ui

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
                cache: "npm"
            
            - name: Build
              run: npm i && npm run react-scripts build
            

